# Generated by Django 5.0 on 2023-12-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchpay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
