# Generated by Django 5.0 on 2023-12-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchpay', '0003_alter_pay_create_date_alter_pay_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutchpay.event'),
        ),
    ]
